chore: specify files field in package.json
minimistjs/minimist pull request #73
Opened 2024-12-12 08:56 UTC by kazushisan

currently the install size is 53.2kB https://packagephobia.com/result?p=minimist

The size is unnecessarily large because the test files, examples and CHANGELOG are all published to npm. This patch will set the files field in package.json to only include the necessary files when publishing. It should reduce the install size to around 12kB 

<img width="828" alt="image" src="https://github.com/user-attachments/assets/0714808e-5f3f-4e48-a56e-74add96fcc6f" />

2024-12-12 16:35 UTC, ljharb requested changes
The tests are very necessarily published to npm; `npm explore foo && npm install && npm test` should always work.

Separately, the files field is dangerous and should never be used - the proper way to control what gets published is an npmignore file.

2024-12-13 03:15 UTC, kazushisan commented
Thank you for your prompt review!

> The tests are very necessarily published to npm; `npm explore foo && npm install && npm test` should always work.

- If you were referring to `npm explore foo && npm install foo && cd node_modules/foo && npm test` and were concerned about tests not working when the package is installed as a dependency, it already doesn't work because the test command relies on a dev dependency. That said, I’m not sure if this is a scenario that users expect to work.
- If you meant `npm explore foo && git clone path/to/foo.git && npm install && npm test`, tests will work regardless of the publish config.

Given that the current configuration increases the package size by 30kB for every dependency relying on minimist, I believe this change could be beneficial. I hope you're open to discussing this further!

2024-12-13 03:20 UTC, ljharb commented
You missed; after npm explore, a bare npm install is run, which installs dev deps.

It’s a scenario that multiple users expect to work, especially the ones that have been around since the beginning of npm.

I’m not concerned with package size on disk - only the size in the application. Files that aren’t consumed in the application  don’t matter, and FUD-producing “phobia” sites don’t make it a valid concern.

2024-12-13 03:39 UTC, kazushisan commented
I understand what you meant now, I wasn't aware of use-cases  running  `npm install` under `node_modules/`. Thanks for clarifying.

2024-12-13 03:39 UTC, closed without merging

2024-12-13 04:41 UTC, shadowspawn commented
For interest, I thought we might have accidentally started including tests and looked into it in #23

Turned out Minimist had included tests in the package for years, probably always, and some people think including the development files is a good thing too. I don't do it myself in other packages I maintain, but also don't consider it a fault when done on purpose, with the benefits/use-cases @ljharb outlined.

2024-12-13 09:59 UTC, kazushisan commented
Thanks! My apologies for not noticing the issue...